import turtle
#turtle.color("white")
turtle.goto(-300,100)
turtle.color("black")
turtle.speed(5)
turtle.pensize(10)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.color("white")
turtle.forward(30)
turtle.color("black")
turtle.forward(60)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(60)

